--INSERT ESTADOS
INSERT INTO estado (nome, sigla)
VALUES
  ('Acre', 'AC'),
  ('Alagoas', 'AL'),
  ('Amapá', 'AP'),
  ('Amazonas', 'AM'),
  ('Bahia', 'BA'),
  ('Ceará', 'CE'),
  ('Distrito Federal', 'DF'),
  ('Espírito Santo', 'ES'),
  ('Goiás', 'GO'),
  ('Maranhão', 'MA'),
  ('Mato Grosso', 'MT'),
  ('Mato Grosso do Sul', 'MS'),
  ('Minas Gerais', 'MG'),
  ('Pará', 'PA'),
  ('Paraíba', 'PB'),
  ('Paraná', 'PR'),
  ('Pernambuco', 'PE'),
  ('Piauí', 'PI'),
  ('Rio de Janeiro', 'RJ'),
  ('Rio Grande do Norte', 'RN'),
  ('Rio Grande do Sul', 'RS'),
  ('Rondônia', 'RO'),
  ('Roraima', 'RR'),
  ('Santa Catarina', 'SC'),
  ('São Paulo', 'SP'),
  ('Sergipe', 'SE'),
  ('Tocantins', 'TO');

-- INSERT CIDADES
INSERT INTO cidade (nome, id_estado) VALUES
  ('Rio Branco', 1),
  ('Macapá', 2),
  ('Maceió', 3),
  ('Manaus', 4),
  ('Salvador', 5),
  ('Fortaleza', 6),
  ('Brasília', 7),
  ('Vitória', 8),
  ('Goiânia', 9),
  ('São Luís', 10),
  ('Cuiabá', 11),
  ('Campo Grande', 12),
  ('Belo Horizonte', 13),
  ('Belém', 14),
  ('João Pessoa', 15),
  ('Curitiba', 16),
  ('Recife', 17),
  ('Teresina', 18),
  ('Rio de Janeiro', 19),
  ('Natal', 20),
  ('Porto Alegre', 21),
  ('Porto Velho', 22),
  ('Boa Vista', 23),
  ('Florianópolis', 24),
  ('São Paulo', 25),
  ('Aracaju', 26),
  ('Palmas', 27);